name: Tests
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: npm run build
